# Default trainer configuration
epochs: 2
steps: 10
trainer_class:
  _target_: ppfn.trainer.PPFNTrainer
  use_amp: false
  grad_clip: 1.0
  aggregate_k_gradients: 1
  verbose: true
  callbacks:
    - _target_: ppfn.trainer.callbacks.MLflowCallback
      log_frequency: 10

  experiment_name: ${experiment_name}


