# Default trainer configuration
epochs: ${dataset.store_prior.n_chunks }
steps:  ${div:${dataset.store_prior.chunk_size},${dataset.store_prior.batch_size}}
# number of batches assuming chunk_size=1008 and batch_size=16
objective: ???
trainer_class:
  _target_: ppfn.trainer.PPFNTrainer
  use_amp: false
  grad_clip: 1.0
  aggregate_k_gradients: 1
  verbose: true


  callbacks: Null