
epochs: 10000 # epochs * steps = total number of training steps.
steps: 10 # marks the number of steps / batches between each evaluation
trainer_class:
  _target_: ppfn.trainer.prototype_trainer.TriStreamTrainer
  train_jointly: False
  warmup_epochs: 1000

  use_amp: True
  grad_clip: 1.0
  aggregate_k_gradients: 1
  verbose: true

  criterion:
    _target_: prototype.harmonic_restart.loss.TriHarmonicLoss
    share_unrelated: ${dataset.dataset_class.share_unrelated}
    use_attn_bonus: False
    criterion:
      _target_: pfns4hpo.bar_distribution.FullSupportBarDistribution
      smoothing: 0.05
      borders:
        _target_: torch.linspace
        start: -7
        end: 7
        steps: ${add:${model.model_class.num_bars}, 1}

  callbacks: Null # placeholder do be overwritten by experiment
