
epochs: 10000 # epochs * steps = total number of training steps.
steps: 10 # marks the number of steps / batches between each evaluation
trainer_class:
  _target_: ppfn.trainer.prototype_trainer.TriStreamTrainer
  train_jointly: False
  warmup_epochs: 1000

  use_amp: True
  grad_clip: 1.0
  aggregate_k_gradients: 1
  verbose: true


  callbacks: Null # placeholder do be overwritten by experiment
