dataset_name: bnn_interpolation_and_unrelated
dataloader:
  _target_: pfns4hpo.priors.utils.PriorDataLoader
  load_path: ${oc.env:DATADIR}priors/${dataset.dataset_name} # fixme: remove _test for final
  n_chunks: 400
  subsample: 1
  store: False # FIXME: once the prior is stored, set to False to stop sampling and just load from disk for efficiency

# method call
store_prior:
  prior:
    _target_: ppfn.dataset.get_batch.same_task.Prior
    get_batch_fn:
      _target_: ppfn.dataset.get_batch.bnn_output_interpolation.get_batch_mixed
      _partial_: True
      share_unrelated_tasks: 0.33

  chunk_size: 5000
  batch_size: 25
  seq_len: 1000
  n_features: 12
  partition: True
  local: True # FIXME: for testing purposes only
  # eval_pos_sampler: # optional. there is a default exp sampler.
  #   _target_: pfns4hpo.priors.utils.get_expon_sep_sampler
  #   seq_len: 1000
  #   base: 2.0
  #   min_eval_pos: 1
