# @package _global_
# Multi-layer model with cross-attention at layers 0 and 2
# 1. Define the base configuration once using an anchor (&)
layer_base: # &layer_logic
  _target_: ppfn.model.experimental.layers.cross_fusion_adapter.CrossFusionAdapter
  d_model: 512
  num_heads: 4
  dropout: 0.1
  use_prenorm: True
  add_linear: False
  use_gate: False
  reuse_attention: False
  C_as_Q: False

trainer:
  trainer_class:
    criterion:
      _target_: ppfn.model.mymodel.multistream_objective.MultiStreamObjective
      criterion:
        _target_: pfns4hpo.bar_distribution.BarDistribution
        borders:
          _target_: torch.linspace
          start: 0
          end: 1
          steps: 1001

model:
  frozen_version: "0.0.1"

  model_class:
    _target_: ppfn.model.mymodel.ppfn_model.PPFN
    stream_parser:
      _target_: ppfn.model.mymodel.stream_parser.StreamParser
      stream_mutations:
        - _target_: ppfn.model.mymodel.stream_mutations.ForceSameQueryMutation

    frozen_model:
      _target_: ppfn.model.baselines.ft_pfn_padding.ft_pfn_padding

    _convert_: partial
    # to avoid instantiation issue that the name should not
    # be in dot notation! therefor, we make it a list of dictionaries and convert them
    # in the class
    interleaved_layers:

      - name: "transformer_encoder.layers.0"
        layer: ${layer_base} #*layer_logic
      - name: "transformer_encoder.layers.1"
        layer: ${layer_base} #*layer_logic
      - name: "transformer_encoder.layers.2"
        layer: ${layer_base} #*layer_logic
      - name: "transformer_encoder.layers.3"
        layer: ${layer_base} #*layer_logic
      - name: "transformer_encoder.layers.4"
        layer: ${layer_base} #*layer_logic
      - name: "transformer_encoder.layers.5"
        layer: ${layer_base} #*layer_logic