## Single layer model for quick testing
#frozen_version: "0.0.1"
#ppfn:
#  _target_: ppfn.model.ppfn.PPFN
#  pre_hook: true
#  interleaved_layers:
#    - name: "transformer_encoder.layers.0"
#      layer:
#        _target_: ppfn.model.ppfn.CrossFusion
#        num_heads: 4
#        dropout: 0.0
