# @package _global_

layer_base: # &layer_logic
  _target_: ppfn.model.mymodel.layers.nw_adapter.NadarayaWatsonAdapter
  d_model: 512
  n_heads: 4
  dropout: 0.1
  nw_dropout: 0.
  reuse_attn: True
  hp_only_attn: True
  seq_len: 1000

trainer:
  objective:
    _target_: ppfn.model.mymodel.multistream_objective.MultiStreamObjective

model:
  frozen_version: "0.0.1"

  model_class:

    _target_: ppfn.model.mymodel.ppfn_model.PPFN
    stream_parser:
      _target_: ppfn.model.mymodel.stream_parser.StreamParser
      stream_mutations:
        - _target_: ppfn.model.mymodel.stream_mutations.ForceSameQueryMutation
        - _target_: ppfn.model.mymodel.stream_mutations.AppendATrainToBTestMutation


    pass_hp_from_frozen: true

    frozen_model:
      _target_: ppfn.model.baselines.ft_pfn_padding.ft_pfn_padding

    _convert_: partial
    # to avoid instantiation issue that the name should not
    # be in dot notation! therefor, we make it a list of dictionaries and convert them
    # in the class
    interleaved_layers:
#      - name:

      - name: "transformer_encoder.layers.0"
        layer: ${layer_base} #*layer_logic
      - name: "transformer_encoder.layers.1"
        layer: ${layer_base} #*layer_logic
      - name: "transformer_encoder.layers.2"
        layer: ${layer_base} #*layer_logic
      - name: "transformer_encoder.layers.3"
        layer: ${layer_base} #*layer_logic
      - name: "transformer_encoder.layers.4"
        layer: ${layer_base} #*layer_logic
      - name: "transformer_encoder.layers.5"
        layer: ${layer_base} #*layer_logic