# Multi-layer model with cross-attention at layers 0 and 2
frozen_version: "0.0.1"

config: 
  d_model: 512
  nhead: 4

model_class:
  
  _target_: ppfn.model.mymodel.ft_ppfn.FT_PPFN
  frozen_model: 
    _target_: ppfn.model.baselines.ft_pfn.ft_pfn

  _convert_: partial
  # to avoid instantantiation issue that the name should not 
  # be in dot notation! therefor, we make it a list of dictionaries and convert them 
  # in the class
  interleaved_layers:
  
    - name: "transformer_encoder.layers.0"
      layer:
        _target_: ppfn.model.mymodel.cross_fusion.CrossFusion
        d_model: ${model.config.d_model}
        num_heads: ${model.config.nhead}
        dropout: 0.1
    - name: "transformer_encoder.layers.1"
      layer:
        _target_: ppfn.model.mymodel.cross_fusion.CrossFusion
        d_model: ${model.config.d_model}
        num_heads: ${model.config.nhead}
        dropout: 0.1
    - name: "transformer_encoder.layers.2"
      layer:
        d_model: ${model.config.d_model}
        _target_: ppfn.model.mymodel.cross_fusion.CrossFusion
        num_heads: ${model.config.nhead}
        dropout: 0.1
    - name: "transformer_encoder.layers.3"
      layer:
        d_model: ${model.config.d_model}
        _target_: ppfn.model.mymodel.cross_fusion.CrossFusion
        num_heads: ${model.config.nhead}
        dropout: 0.1
    - name: "transformer_encoder.layers.4"
      layer:
        d_model: ${model.config.d_model}
        _target_: ppfn.model.mymodel.cross_fusion.CrossFusion
        num_heads: ${model.config.nhead}
        dropout: 0.1
    - name: "transformer_encoder.layers.5"
      layer:
        d_model: ${model.config.d_model}
        _target_: ppfn.model.mymodel.cross_fusion.CrossFusion
        num_heads: ${model.config.nhead}
