# @package _global_
# Multi-layer model with cross-attention at layers 0 and 2
# 1. Define the base configuration once using an anchor (&)
layer_base: # &layer_logic
  _target_: ppfn.model.mymodel.layers.mha_adapter.MHA_StreamAdapter
  d_model: 512
  n_heads: 4
  dropout: 0.1

trainer:
  objective:
    _target_: ppfn.model.mymodel.multistream_objective.MultiStreamObjective

model:
  frozen_version: "0.0.1"

  model_class:
    _target_: ppfn.model.mymodel.ppfn_model.PPFN
    pass_hp_from_frozen: False
    pass_hp_as_rawpaded: False
    stream_parser:
      _target_: ppfn.model.mymodel.stream_parser.StreamParser


    frozen_model:
      _target_: ppfn.model.baselines.ft_pfn.ft_pfn

    _convert_: partial
    # to avoid instantiation issue that the name should not
    # be in dot notation! therefor, we make it a list of dictionaries and convert them
    # in the class
    interleaved_layers:

      - name: "transformer_encoder.layers.0"
        layer: ${layer_base} #*layer_logic
#      - name: "transformer_encoder.layers.1"
#        layer: ${layer_base} #*layer_logic
#      - name: "transformer_encoder.layers.2"
#        layer: ${layer_base} #*layer_logic
#      - name: "transformer_encoder.layers.3"
#        layer: ${layer_base} #*layer_logic
#      - name: "transformer_encoder.layers.4"
#        layer: ${layer_base} #*layer_logic
#      - name: "transformer_encoder.layers.5"
#        layer: ${layer_base} #*layer_logic