# @package _global_

model:
  frozen_version: "0.0.1"

  model_class:
    _target_: prototype.harmonic_restart.model.TriHarmonicModel
    d_model: 128
    nhead: 4
    dropout: 0.1
    num_bars: 250
    use_freq_enc_x: True
    use_cross_attn: True

    cross_attn_layer:
      _target_: prototype.harmonic_restart.invariant_layer.ManifoldCrossAttnLayer
      d_model: 128
      proj_depth: 2
      dim_feedforward: 128
      nhead: 4
      update_C_train: True
      scale_factor: 0.25
      use_stacked_self_attn: True
      use_aux_loss: True
      aux_loss:
        _target_: prototype.harmonic_restart.invariant_layer.ManifoldAlignmentCriterion
        top_k: 3
        loss_scale: 0.1


trainer:
  trainer_class:
    criterion:
      _target_: prototype.harmonic_restart.loss.TriHarmonicLoss
      share_unrelated: ${dataset.dataset_class.share_unrelated}
      use_attn_bonus: False
      criterion:
        _target_: pfns4hpo.bar_distribution.FullSupportBarDistribution
        smoothing: 0.05
        borders:
          _target_: torch.linspace
          start: -7
          end: 7
          steps: ${add:${model.model_class.num_bars}, 1}
