ckpt:
  _target_: ppfn.trainer.callbacks.checkpoint_callback.CheckpointCallback
  save_dir: ${hydra:run.dir}/checkpoints/
  name: "best_nll_CA"
  mode: "min"
  monitor: "nll/C-A"
  resume_from: ${checkpoint}