ckpt:
  _target_: ppfn.trainer.callbacks.checkpoint.CheckpointCallback
  frequency:  ${validation_frequency}
  save_dir: ${hydra:run.dir}/checkpoints/
  name: "best_nll_CA"
  mode: "min"
  monitor: "nll/C-A"
  resume_from: ${checkpoint}